/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.cassandra.thrift;
/*
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 */


import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

/**
 * Increment and decrement of counters.
 * @param counter the delta to apply to the counter (can be positive or negative)
 * @param timestamp the timestamp for the insertion. This plays a similar role
 *        to the timestamp of a column, even though new update do not
 *        overwrite old ones as the counter are delta based.
 * @param uuid an optional unique identifier of this update. This is use to allow replaying a
 *        CounterUpdate in case of failure (TimeoutException mainly). In such eventuality,
 *        you can safely reinsert the same update (with the same uuid) without the risk
 *        of the update being counted twice. You can skip this argument if you can afford to
 *        loose some increments in failure case but need slightly better write performances.
 */
public class CounterUpdate implements TBase<CounterUpdate, CounterUpdate._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("CounterUpdate");

  private static final TField COUNTER_FIELD_DESC = new TField("counter", TType.STRUCT, (short)1);
  private static final TField UUID_FIELD_DESC = new TField("uuid", TType.STRING, (short)2);

  public Counter counter;
  public ByteBuffer uuid;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    COUNTER((short)1, "counter"),
    UUID((short)2, "uuid");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COUNTER
          return COUNTER;
        case 2: // UUID
          return UUID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COUNTER, new FieldMetaData("counter", TFieldRequirementType.REQUIRED, 
        new StructMetaData(TType.STRUCT, Counter.class)));
    tmpMap.put(_Fields.UUID, new FieldMetaData("uuid", TFieldRequirementType.OPTIONAL, 
        new FieldValueMetaData(TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(CounterUpdate.class, metaDataMap);
  }

  public CounterUpdate() {
  }

  public CounterUpdate(
    Counter counter)
  {
    this();
    this.counter = counter;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CounterUpdate(CounterUpdate other) {
    if (other.isSetCounter()) {
      this.counter = new Counter(other.counter);
    }
    if (other.isSetUuid()) {
      this.uuid = TBaseHelper.copyBinary(other.uuid);
;
    }
  }

  public CounterUpdate deepCopy() {
    return new CounterUpdate(this);
  }

  @Override
  public void clear() {
    this.counter = null;
    this.uuid = null;
  }

  public Counter getCounter() {
    return this.counter;
  }

  public CounterUpdate setCounter(Counter counter) {
    this.counter = counter;
    return this;
  }

  public void unsetCounter() {
    this.counter = null;
  }

  /** Returns true if field counter is set (has been asigned a value) and false otherwise */
  public boolean isSetCounter() {
    return this.counter != null;
  }

  public void setCounterIsSet(boolean value) {
    if (!value) {
      this.counter = null;
    }
  }

  public byte[] getUuid() {
    setUuid(TBaseHelper.rightSize(uuid));
    return uuid.array();
  }

  public ByteBuffer BufferForUuid() {
    return uuid;
  }

  public CounterUpdate setUuid(byte[] uuid) {
    setUuid(ByteBuffer.wrap(uuid));
    return this;
  }

  public CounterUpdate setUuid(ByteBuffer uuid) {
    this.uuid = uuid;
    return this;
  }

  public void unsetUuid() {
    this.uuid = null;
  }

  /** Returns true if field uuid is set (has been asigned a value) and false otherwise */
  public boolean isSetUuid() {
    return this.uuid != null;
  }

  public void setUuidIsSet(boolean value) {
    if (!value) {
      this.uuid = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COUNTER:
      if (value == null) {
        unsetCounter();
      } else {
        setCounter((Counter)value);
      }
      break;

    case UUID:
      if (value == null) {
        unsetUuid();
      } else {
        setUuid((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COUNTER:
      return getCounter();

    case UUID:
      return getUuid();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COUNTER:
      return isSetCounter();
    case UUID:
      return isSetUuid();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CounterUpdate)
      return this.equals((CounterUpdate)that);
    return false;
  }

  public boolean equals(CounterUpdate that) {
    if (that == null)
      return false;

    boolean this_present_counter = true && this.isSetCounter();
    boolean that_present_counter = true && that.isSetCounter();
    if (this_present_counter || that_present_counter) {
      if (!(this_present_counter && that_present_counter))
        return false;
      if (!this.counter.equals(that.counter))
        return false;
    }

    boolean this_present_uuid = true && this.isSetUuid();
    boolean that_present_uuid = true && that.isSetUuid();
    if (this_present_uuid || that_present_uuid) {
      if (!(this_present_uuid && that_present_uuid))
        return false;
      if (!this.uuid.equals(that.uuid))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_counter = true && (isSetCounter());
    builder.append(present_counter);
    if (present_counter)
      builder.append(counter);

    boolean present_uuid = true && (isSetUuid());
    builder.append(present_uuid);
    if (present_uuid)
      builder.append(uuid);

    return builder.toHashCode();
  }

  public int compareTo(CounterUpdate other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    CounterUpdate typedOther = (CounterUpdate)other;

    lastComparison = Boolean.valueOf(isSetCounter()).compareTo(typedOther.isSetCounter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCounter()) {
      lastComparison = TBaseHelper.compareTo(this.counter, typedOther.counter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUuid()).compareTo(typedOther.isSetUuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUuid()) {
      lastComparison = TBaseHelper.compareTo(this.uuid, typedOther.uuid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // COUNTER
          if (field.type == TType.STRUCT) {
            this.counter = new Counter();
            this.counter.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // UUID
          if (field.type == TType.STRING) {
            this.uuid = iprot.readBinary();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.counter != null) {
      oprot.writeFieldBegin(COUNTER_FIELD_DESC);
      this.counter.write(oprot);
      oprot.writeFieldEnd();
    }
    if (this.uuid != null) {
      if (isSetUuid()) {
        oprot.writeFieldBegin(UUID_FIELD_DESC);
        oprot.writeBinary(this.uuid);
        oprot.writeFieldEnd();
      }
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CounterUpdate(");
    boolean first = true;

    sb.append("counter:");
    if (this.counter == null) {
      sb.append("null");
    } else {
      sb.append(this.counter);
    }
    first = false;
    if (isSetUuid()) {
      if (!first) sb.append(", ");
      sb.append("uuid:");
      if (this.uuid == null) {
        sb.append("null");
      } else {
        TBaseHelper.toString(this.uuid, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (counter == null) {
      throw new TProtocolException("Required field 'counter' was not present! Struct: " + toString());
    }
  }

}

